### ISSUE TITLE
In node v10.0.0, build failed

### ISSUE THREAD

**Issue by dotneet** [Level/leveldown#448]
```
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
```

maybe nan package is old.

**Comment by ralphtheninja** [comment]
It builds on linux so I assume you're on windows? Can you provide more of the log please.

**Comment by ralphtheninja** [comment]
It seems to build fine on appveyor as well.

**Comment by dotneet** [comment]
sorry. maybe this was caused by another package.
this error did not happend, with clean environment.

**Comment by Arcanemagus** [comment]
It looks like `leveldown@3.0.0` works just fine with Node.js v10.0.0, but older versions (tested with `leveldown@1.9.0`) shows similar errors to the above:

```
c:\temp\foo\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..\src\batch.cc) [C:\temp\foo\node_modules\leveldown\build\leveldown.vcxproj]
  c:\users\abneyl\.node-gyp\10.0.0\include\node\v8.h(3111): note: see declaration of 'v8::Object' (compiling source file ..\src\batch.cc)
```

**Comment by arcfide** [comment]
I am also seeing this on a fresh installation trying to install leveldown@1.7.2

**Comment by ralphtheninja** [comment]
I can confirm the problem. It's a bit of a shame, but apparently if you want leveldown on the latest node, you must upgrade for now.

I did a quick check and it seems that v2.0.2 and up works with node 10 but v2.0.1 and down are broken.
