### ISSUE TITLE
Weird core dump on Ubuntu 15.10

### ISSUE THREAD

**Issue by binarykitchen** [Level/leveldown#269]
See https://github.com/nodejs/node/issues/6036 which has all the details. The core dump tells me that it comes from leveldown. So, reporting it here.

My node.js app crashes with this output in the command line:

```
*** Error in `node': corrupted double-linked list: 0x00007f1c5800cc40 ***
```

Using version "1.4.4" of leveldown.

Here a long copy of the first interesting lines of that core dump:

```
# michael-heuberger @ M1 in /var/crash [21:45:28] 
$ cat _usr_bin_nodejs.1000.crash 
ProblemType: Crash
Architecture: amd64
CrashCounter: 1
CurrentDesktop: Unity
Date: Wed Apr  6 21:39:00 2016
DistroRelease: Ubuntu 15.10
ExecutablePath: /usr/bin/nodejs
ExecutableTimestamp: 1459492516
ProcCmdline: node /home/michael-heuberger/binarykitchen/code/videomail.io/src/server.js
ProcCwd: /home/michael-heuberger/binarykitchen/code/videomail.io
ProcEnviron:
 LC_TIME=en_NZ.UTF-8
 LANGUAGE=en_NZ:en_AU:en_GB:en
 LC_MONETARY=en_NZ.UTF-8
 LC_CTYPE=en_NZ.UTF-8
 TERM=xterm
 PATH=(custom, user)
 LC_ADDRESS=en_NZ.UTF-8
 XDG_RUNTIME_DIR=<set>
 LANG=en_NZ.UTF-8
 LC_TELEPHONE=en_NZ.UTF-8
 SHELL=/bin/zsh
 LC_NAME=en_NZ.UTF-8
 LC_MEASUREMENT=en_NZ.UTF-8
 LC_IDENTIFICATION=en_NZ.UTF-8
 LC_NUMERIC=en_NZ.UTF-8
 LC_PAPER=en_NZ.UTF-8
ProcMaps:
 00400000-0178f000 r-xp 00000000 08:12 9843169                            /usr/bin/nodejs
 0198e000-0198f000 r--p 0138e000 08:12 9843169                            /usr/bin/nodejs
 0198f000-019a7000 rw-p 0138f000 08:12 9843169                            /usr/bin/nodejs
 019a7000-019b8000 rw-p 00000000 00:00 0 
 0379a000-041e9000 rw-p 00000000 00:00 0                                  [heap]
 1042200000-1042300000 rw-p 00000000 00:00 0 
 12d64000000-12d64100000 rw-p 00000000 00:00 0 
 40b69800000-40b69814000 rw-p 00000000 00:00 0 
 a3fe3000000-a3fe3100000 rw-p 00000000 00:00 0 
 b331cd00000-b331ce00000 rw-p 00000000 00:00 0 
 cd143b00000-cd143c00000 rw-p 00000000 00:00 0 
 11111e800000-11111e900000 rw-p 00000000 00:00 0 
 1565c3d00000-1565c3e00000 rw-p 00000000 00:00 0 
 1949d8d00000-1949d8e00000 rw-p 00000000 00:00 0 
 1b2fdcc00000-1b2fdcd00000 rw-p 00000000 00:00 0 
 1b6c82968000-1b6c829a8000 rw-p 00000000 00:00 0 
 1b6c829a8000-1b6c82b68000 ---p 00000000 00:00 0 
 1c2242400000-1c22424dd000 rw-p 00000000 00:00 0 
 1ed52c248000-1ed52c280000 ---p 00000000 00:00 0 
 1ed52c280000-1ed52c2a0000 rw-p 00000000 00:00 0 
 1ed52c2a0000-1ed52c2a8000 ---p 00000000 00:00 0 
 1f5f3e1a7000-1f5f3e5a7000 rw-p 00000000 00:00 0 
 1f9fe5800000-1f9fe5900000 rw-p 00000000 00:00 0 
 1ff924200000-1ff924300000 rw-p 00000000 00:00 0 
 2008cf000000-2008cf100000 rw-p 00000000 00:00 0 
 201889800000-201889900000 rw-p 00000000 00:00 0 
 203524f00000-203525000000 rw-p 00000000 00:00 0 
 20822aa00000-20822ab00000 rw-p 00000000 00:00 0 
 2289e6d00000-2289e6e00000 rw-p 00000000 00:00 0 
 2306c5d00000-2306c5e00000 rw-p 00000000 00:00 0 
 285504f00000-285505000000 rw-p 00000000 00:00 0 
 2b356aa00000-2b356ab00000 rw-p 00000000 00:00 0 
 2b79fcc00000-2b79fcd05000 rw-p 00000000 00:00 0 
 2d20a2200000-2d20a2300000 rw-p 00000000 00:00 0 
 2d9223500000-2d9223600000 rw-p 00000000 00:00 0 
 2e279ff00000-2e27a00ce000 rw-p 00000000 00:00 0 
 2f86d8b00000-2f86d8cce000 rw-p 00000000 00:00 0 
 2f87e7800000-2f87e7900000 rw-p 00000000 00:00 0 
 301394700000-301394800000 rw-p 00000000 00:00 0 
 313186900000-313186a00000 rw-p 00000000 00:00 0 
 315621c03000-315621e00000 ---p 00000000 00:00 0 
 315621e00000-315621e05000 rw-p 00000000 00:00 0 
 315621e05000-315621e06000 ---p 00000000 00:00 0 
 315621e06000-315621e07000 rwxp 00000000 00:00 0 
 315621e07000-315621f00000 ---p 00000000 00:00 0 
 315621f00000-315621f05000 rw-p 00000000 00:00 0 
 315621f05000-315621f06000 ---p 00000000 00:00 0 
 315621f06000-315621f07000 rwxp 00000000 00:00 0 
 315621f07000-315622000000 ---p 00000000 00:00 0 
 315622000000-315622005000 rw-p 00000000 00:00 0 
 315622005000-315622006000 ---p 00000000 00:00 0 
 315622006000-315622007000 rwxp 00000000 00:00 0 
 315622007000-315622100000 ---p 00000000 00:00 0 
 315622100000-315622105000 rw-p 00000000 00:00 0 
 315622105000-315622106000 ---p 00000000 00:00 0 
 315622106000-31562214b000 rwxp 00000000 00:00 0 
 31562214b000-315622200000 ---p 00000000 00:00 0 
 315622200000-315622205000 rw-p 00000000 00:00 0 
 315622205000-315622206000 ---p 00000000 00:00 0 
 315622206000-3156222ff000 rwxp 00000000 00:00 0 
 3156222ff000-315622300000 ---p 00000000 00:00 0 
 315622300000-315622305000 rw-p 00000000 00:00 0 
 315622305000-315622306000 ---p 00000000 00:00 0 
 315622306000-3156223ff000 rwxp 00000000 00:00 0 
 3156223ff000-315622400000 ---p 00000000 00:00 0 
 315622400000-315622405000 rw-p 00000000 00:00 0 
 315622405000-315622406000 ---p 00000000 00:00 0 
 315622406000-3156224ff000 rwxp 00000000 00:00 0 
 3156224ff000-315622500000 ---p 00000000 00:00 0 
 315622500000-315622505000 rw-p 00000000 00:00 0 
 315622505000-315622506000 ---p 00000000 00:00 0 
 315622506000-3156225ff000 rwxp 00000000 00:00 0 
 3156225ff000-315622600000 ---p 00000000 00:00 0 
 315622600000-315622605000 rw-p 00000000 00:00 0 
 315622605000-315622606000 ---p 00000000 00:00 0 
 315622606000-3156226ff000 rwxp 00000000 00:00 0 
 3156226ff000-315622700000 ---p 00000000 00:00 0 
 315622700000-315622705000 rw-p 00000000 00:00 0 
 315622705000-315622706000 ---p 00000000 00:00 0 
 315622706000-3156227ff000 rwxp 00000000 00:00 0 
 3156227ff000-315622800000 ---p 00000000 00:00 0 
 315622800000-315622805000 rw-p 00000000 00:00 0 
 315622805000-315622806000 ---p 00000000 00:00 0 
 315622806000-3156228ff000 rwxp 00000000 00:00 0 
 3156228ff000-315622900000 ---p 00000000 00:00 0 
 315622900000-315622905000 rw-p 00000000 00:00 0 
 315622905000-315622906000 ---p 00000000 00:00 0 
 315622906000-3156229ff000 rwxp 00000000 00:00 0 
 3156229ff000-315641c03000 ---p 00000000 00:00 0 
 319bed100000-319bed200000 rw-p 00000000 00:00 0 
 31a28e200000-31a28e300000 rw-p 00000000 00:00 0 
 322c99000000-322c99100000 rw-p 00000000 00:00 0 
 327647600000-327647700000 rw-p 00000000 00:00 0 
 35be13f00000-35be14000000 rw-p 00000000 00:00 0 
 362e73800000-362e73900000 rw-p 00000000 00:00 0 
 367f32000000-367f33000000 rw-p 00000000 00:00 0 
 367f33000000-367f34000000 rw-p 00000000 00:00 0 
 39f5a7a00000-39f5a7b00000 rw-p 00000000 00:00 0 
 3aba029f8000-3aba029f9000 r-xp 00000000 00:00 0 
 3bc1ed100000-3bc1ed200000 rw-p 00000000 00:00 0 
 3e3aed400000-3e3aed500000 rw-p 00000000 00:00 0 
 3f27ba900000-3f27baa00000 rw-p 00000000 00:00 0 
 3f726e900000-3f726ea00000 rw-p 00000000 00:00 0 
 7f1c4c000000-7f1c4c029000 rw-p 00000000 00:00 0 
 7f1c4c029000-7f1c50000000 ---p 00000000 00:00 0 
 7f1c54000000-7f1c54029000 rw-p 00000000 00:00 0 
 7f1c54029000-7f1c58000000 ---p 00000000 00:00 0 
 7f1c58000000-7f1c58030000 rw-p 00000000 00:00 0 
 7f1c58030000-7f1c5c000000 ---p 00000000 00:00 0 
 7f1c5c000000-7f1c5c021000 rw-p 00000000 00:00 0 
 7f1c5c021000-7f1c60000000 ---p 00000000 00:00 0 
 7f1c61408000-7f1c61409000 ---p 00000000 00:00 0 
 7f1c61409000-7f1c61c09000 rw-p 00000000 00:00 0                          [stack:10102]
 7f1c61c09000-7f1c61c0a000 ---p 00000000 00:00 0 
 7f1c61c0a000-7f1c6240a000 rw-p 00000000 00:00 0                          [stack:10101]
 7f1c6240a000-7f1c6240b000 ---p 00000000 00:00 0 
 7f1c6240b000-7f1c62c0b000 rw-p 00000000 00:00 0                          [stack:10100]
 7f1c62c0b000-7f1c62c0c000 ---p 00000000 00:00 0 
 7f1c62c0c000-7f1c6340c000 rw-p 00000000 00:00 0                          [stack:10099]
 7f1c6340c000-7f1c6347f000 r-xp 00000000 08:21 18219566                   /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/leveldown/build/Release/leveldown.node
 7f1c6347f000-7f1c6367f000 ---p 00073000 08:21 18219566                   /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/leveldown/build/Release/leveldown.node
 7f1c6367f000-7f1c63682000 rw-p 00073000 08:21 18219566                   /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/leveldown/build/Release/leveldown.node
 7f1c63682000-7f1c63687000 r-xp 00000000 08:12 9833502                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
 7f1c63687000-7f1c63886000 ---p 00005000 08:12 9833502                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
 7f1c63886000-7f1c63887000 r--p 00004000 08:12 9833502                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
 7f1c63887000-7f1c63888000 rw-p 00005000 08:12 9833502                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
 7f1c63888000-7f1c6388a000 r-xp 00000000 08:12 9838505                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
 7f1c6388a000-7f1c63a8a000 ---p 00002000 08:12 9838505                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
 7f1c63a8a000-7f1c63a8b000 r--p 00002000 08:12 9838505                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
 7f1c63a8b000-7f1c63a8c000 rw-p 00003000 08:12 9838505                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
 7f1c63a8c000-7f1c63a95000 r-xp 00000000 08:12 9833636                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
 7f1c63a95000-7f1c63c94000 ---p 00009000 08:12 9833636                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
 7f1c63c94000-7f1c63c95000 r--p 00008000 08:12 9833636                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
 7f1c63c95000-7f1c63c96000 rw-p 00009000 08:12 9833636                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
 7f1c63c96000-7f1c63c9e000 r-xp 00000000 08:12 9833640                    /usr/lib/x86_64-linux-gnu/libxcb-render.so.0.0.0
 7f1c63c9e000-7f1c63e9e000 ---p 00008000 08:12 9833640                    /usr/lib/x86_64-linux-gnu/libxcb-render.so.0.0.0
 7f1c63e9e000-7f1c63e9f000 r--p 00008000 08:12 9833640                    /usr/lib/x86_64-linux-gnu/libxcb-render.so.0.0.0
 7f1c63e9f000-7f1c63ea0000 rw-p 00009000 08:12 9833640                    /usr/lib/x86_64-linux-gnu/libxcb-render.so.0.0.0
 7f1c63ea0000-7f1c63ea2000 r-xp 00000000 08:12 9833644                    /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
 7f1c63ea2000-7f1c640a2000 ---p 00002000 08:12 9833644                    /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
 7f1c640a2000-7f1c640a3000 r--p 00002000 08:12 9833644                    /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
... goes down to 20MB further
```

Any clues what this could be?

**Comment by binarykitchen** [comment]
Btw, I am loading leveldown through level-party's latest version 3.0.4 ...

**Comment by ralphtheninja** [comment]
@binarykitchen Can you reproduce this or does it happen randomly?

**Comment by binarykitchen** [comment]
Happens always in when I run the app in my private repo.

**Comment by ralphtheninja** [comment]
@binarykitchen It would help a great deal if you could compile the leveldown binaries in debug mode, e.g. `node-gyp rebuild --debug`, so we can get more information from the core dump

**Comment by binarykitchen** [comment]
@ralphtheninja hmmm, i tried but am having issues. let me write down the steps i did:

1. `npm i -g node-gyp` installed the latest, 3.3.1
2. in my add, cd'd to ./node_modules/leveldown
3. called `node-gyp configure`
4. then `node-gyp rebuild --debug`
5. then back in the root folder, started the app with `gulp watch`
6. another node module crashed with

```
module.js:327
    throw err;
    ^

Error: Cannot find module './build/Release/sharp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    ...
```

but i didn't touch sharp at all. how come?

**Comment by ralphtheninja** [comment]
> but i didn't touch sharp at all. how come?

Umm odd, I have no idea why sharp would be rebuild by node-gyp in this case.

**Comment by binarykitchen** [comment]
@ralphtheninja yep, very odd. And if you look at the core dump https://gist.github.com/binarykitchen/9ac53ad6810e1a2c23e8d636422f59e9 you can see the backtrace goes from `leveldown.node` to `libXdmcp.so.6.0.0` and further down you see `libvips-cpp.so.42.3.3` which is installed by sharp. Something does not look good here.

**Comment by ralphtheninja** [comment]
@binarykitchen What's the status of this? Have you tried out leveldown 1.5.0? It builds on leveldb 1.19.

**Comment by binarykitchen** [comment]
no idea, bumped to ubuntu 16.04 and all good here

**Comment by ralphtheninja** [comment]
Closing this. Please re-open if needed.
